PROJECT_PATH = 'D:\\VQA'
VAL_DATA_TYPE = 'val2014'
DATA_PATH = 'D:\\VQA\\coco_qa'
VERSION_TYPE ='v2_'
DATA_TYPE = 'mscoco'
TASK_TYPE = 'OpenEnded'
TRAIN_DATA_TYPE = 'train2014'
TRAIN_DATA_PATH = '{}\\images\\{}\\'.format(DATA_PATH,TRAIN_DATA_TYPE)
VAL_DATA_PATH = '{}\\images\\{}\\'.format(DATA_PATH,VAL_DATA_TYPE)
ANSWERS_DICT_PATH = "dict\\answers_dict.json"
QUESTIONS_DICT_PATH = "dict\\questions_dict.json"
VGG19_WEIGHTS_AND_BIASE_PATH = "vgg19\\imagenet-vgg-verydeep-19.mat"
RUN_DATA_PATH = "data\\"
RUN_DATA_RECORDER = RUN_DATA_PATH + "data.json"